# name
name: BeagleBone Enhanced IO

# description
description: Documentation site for BeagleBone Enhanced IO

# site theme
theme: jekyll-theme-minimal

# author
author: UND-ARC
author_email: 

show_downloads: true
